// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/proto/radar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TradeData represents a single trade from an exchange.
type TradeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // Unique trade ID (from exchange or generated)
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                      // Exchange name (e.g., "nobitex", "wallex")
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                          // Trading pair (e.g., "BTC/IRT", "ETH/USDT")
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                          // Trade price in quote currency
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`                        // Trade volume in base currency
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // Total value (price * volume)
	Side          string                 `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`                              // Trade direction: "buy", "sell", or "all"
	Time          string                 `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`                              // Trade timestamp in RFC3339 format
	UsdtPrice     float64                `protobuf:"fixed64,9,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"` // USDT/IRT price at trade time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeData) Reset() {
	*x = TradeData{}
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeData) ProtoMessage() {}

func (x *TradeData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeData.ProtoReflect.Descriptor instead.
func (*TradeData) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{0}
}

func (x *TradeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TradeData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeData) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeData) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TradeData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TradeData) GetUsdtPrice() float64 {
	if x != nil {
		return x.UsdtPrice
	}
	return 0
}

// TradeDataBatch contains multiple trades (used by WebSocket scrapers).
type TradeDataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*TradeData           `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeDataBatch) Reset() {
	*x = TradeDataBatch{}
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeDataBatch) ProtoMessage() {}

func (x *TradeDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeDataBatch.ProtoReflect.Descriptor instead.
func (*TradeDataBatch) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{1}
}

func (x *TradeDataBatch) GetTrades() []*TradeData {
	if x != nil {
		return x.Trades
	}
	return nil
}

// OHLCData represents a single candlestick (Open, High, Low, Close).
type OHLCData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique ID: exchange-symbol-interval-openTime
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                       // Exchange name
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // Trading pair
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`                       // Timeframe: "1d", "4h", "1h", "15m", etc.
	Open          float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`                             // Opening price
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`                             // Highest price
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`                               // Lowest price
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`                           // Closing price
	Volume        float64                `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`                         // Trading volume
	UsdtPrice     float64                `protobuf:"fixed64,10,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"` // USDT/IRT price at candle close
	OpenTime      string                 `protobuf:"bytes,11,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`      // Candle open time in RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLCData) Reset() {
	*x = OHLCData{}
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLCData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCData) ProtoMessage() {}

func (x *OHLCData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCData.ProtoReflect.Descriptor instead.
func (*OHLCData) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{2}
}

func (x *OHLCData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OHLCData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OHLCData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OHLCData) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *OHLCData) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLCData) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLCData) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLCData) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *OHLCData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OHLCData) GetUsdtPrice() float64 {
	if x != nil {
		return x.UsdtPrice
	}
	return 0
}

func (x *OHLCData) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

// OHLCDataBatch contains multiple OHLC candles.
type OHLCDataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*OHLCData            `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLCDataBatch) Reset() {
	*x = OHLCDataBatch{}
	mi := &file_internal_proto_radar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLCDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCDataBatch) ProtoMessage() {}

func (x *OHLCDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCDataBatch.ProtoReflect.Descriptor instead.
func (*OHLCDataBatch) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{3}
}

func (x *OHLCDataBatch) GetCandles() []*OHLCData {
	if x != nil {
		return x.Candles
	}
	return nil
}

var File_internal_proto_radar_proto protoreflect.FileDescriptor

const file_internal_proto_radar_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/radar.proto\x12\x05proto\"\xe0\x01\n" +
	"\tTradeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04side\x18\a \x01(\tR\x04side\x12\x12\n" +
	"\x04time\x18\b \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\t \x01(\x01R\tusdtPrice\":\n" +
	"\x0eTradeDataBatch\x12(\n" +
	"\x06trades\x18\x01 \x03(\v2\x10.proto.TradeDataR\x06trades\"\x8e\x02\n" +
	"\bOHLCData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\t \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\n" +
	" \x01(\x01R\tusdtPrice\x12\x1b\n" +
	"\topen_time\x18\v \x01(\tR\bopenTime\":\n" +
	"\rOHLCDataBatch\x12)\n" +
	"\acandles\x18\x01 \x03(\v2\x0f.proto.OHLCDataR\acandlesB\x1eZ\x1cnobitex/radar/internal/protob\x06proto3"

var (
	file_internal_proto_radar_proto_rawDescOnce sync.Once
	file_internal_proto_radar_proto_rawDescData []byte
)

func file_internal_proto_radar_proto_rawDescGZIP() []byte {
	file_internal_proto_radar_proto_rawDescOnce.Do(func() {
		file_internal_proto_radar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)))
	})
	return file_internal_proto_radar_proto_rawDescData
}

var file_internal_proto_radar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_radar_proto_goTypes = []any{
	(*TradeData)(nil),      // 0: proto.TradeData
	(*TradeDataBatch)(nil), // 1: proto.TradeDataBatch
	(*OHLCData)(nil),       // 2: proto.OHLCData
	(*OHLCDataBatch)(nil),  // 3: proto.OHLCDataBatch
}
var file_internal_proto_radar_proto_depIdxs = []int32{
	0, // 0: proto.TradeDataBatch.trades:type_name -> proto.TradeData
	2, // 1: proto.OHLCDataBatch.candles:type_name -> proto.OHLCData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_radar_proto_init() }
func file_internal_proto_radar_proto_init() {
	if File_internal_proto_radar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_radar_proto_goTypes,
		DependencyIndexes: file_internal_proto_radar_proto_depIdxs,
		MessageInfos:      file_internal_proto_radar_proto_msgTypes,
	}.Build()
	File_internal_proto_radar_proto = out.File
	file_internal_proto_radar_proto_goTypes = nil
	file_internal_proto_radar_proto_depIdxs = nil
}
