// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/proto/radar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TradeData represents a single trade from an exchange.
type TradeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // Unique trade ID (from exchange or generated)
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                      // Exchange name (e.g., "nobitex", "wallex")
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                          // Trading pair (e.g., "BTC/IRT", "ETH/USDT")
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                          // Trade price in quote currency
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`                        // Trade volume in base currency
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // Total value (price * volume)
	Side          string                 `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`                              // Trade direction: "buy", "sell", or "all"
	Time          string                 `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`                              // Trade timestamp in RFC3339 format
	UsdtPrice     float64                `protobuf:"fixed64,9,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"` // USDT/IRT price at trade time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeData) Reset() {
	*x = TradeData{}
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeData) ProtoMessage() {}

func (x *TradeData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeData.ProtoReflect.Descriptor instead.
func (*TradeData) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{0}
}

func (x *TradeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TradeData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeData) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeData) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TradeData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TradeData) GetUsdtPrice() float64 {
	if x != nil {
		return x.UsdtPrice
	}
	return 0
}

// OHLCData represents a single candlestick (Open, High, Low, Close).
type CandleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique ID: exchange-symbol-interval-openTime
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                       // Exchange name
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // Trading pair
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`                       // Timeframe: "1d", "4h", "1h", "15m", etc.
	Open          float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`                             // Opening price
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`                             // Highest price
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`                               // Lowest price
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`                           // Closing price
	Volume        float64                `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`                         // Trading volume
	UsdtPrice     float64                `protobuf:"fixed64,10,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"` // USDT/IRT price at candle close
	OpenTime      string                 `protobuf:"bytes,11,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`      // Candle open time in RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandleData) Reset() {
	*x = CandleData{}
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleData) ProtoMessage() {}

func (x *CandleData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleData.ProtoReflect.Descriptor instead.
func (*CandleData) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{1}
}

func (x *CandleData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandleData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CandleData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CandleData) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *CandleData) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CandleData) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CandleData) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CandleData) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CandleData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CandleData) GetUsdtPrice() float64 {
	if x != nil {
		return x.UsdtPrice
	}
	return 0
}

func (x *CandleData) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

// OrderLevel represents a single price level in the order book.
// We keep this lightweight as it will be repeated hundreds of times.
type OrderLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume        float64                `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderLevel) Reset() {
	*x = OrderLevel{}
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLevel) ProtoMessage() {}

func (x *OrderLevel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLevel.ProtoReflect.Descriptor instead.
func (*OrderLevel) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{2}
}

func (x *OrderLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderLevel) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// OrderBookSnapshot represents the full state of the market depth at one moment.
// Instead of repeating 'exchange' and 'symbol' for every row, we group them here.
type OrderBookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique snapshot ID (UUID or generated)
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                       // Exchange name (e.g. "nobitex")
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // Trading pair (e.g. "BTC/IRT")
	Bids          []*OrderLevel          `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`                               // List of Buy orders
	Asks          []*OrderLevel          `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`                               // List of Sell orders
	LastUpdate    string                 `protobuf:"bytes,6,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"` // Exchange timestamp in RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookSnapshot) Reset() {
	*x = OrderBookSnapshot{}
	mi := &file_internal_proto_radar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookSnapshot) ProtoMessage() {}

func (x *OrderBookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_radar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookSnapshot.ProtoReflect.Descriptor instead.
func (*OrderBookSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_radar_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBookSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderBookSnapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderBookSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBookSnapshot) GetBids() []*OrderLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookSnapshot) GetAsks() []*OrderLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookSnapshot) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

var File_internal_proto_radar_proto protoreflect.FileDescriptor

const file_internal_proto_radar_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/radar.proto\x12\x05proto\"\xe0\x01\n" +
	"\tTradeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04side\x18\a \x01(\tR\x04side\x12\x12\n" +
	"\x04time\x18\b \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\t \x01(\x01R\tusdtPrice\"\x90\x02\n" +
	"\n" +
	"CandleData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\t \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\n" +
	" \x01(\x01R\tusdtPrice\x12\x1b\n" +
	"\topen_time\x18\v \x01(\tR\bopenTime\":\n" +
	"\n" +
	"OrderLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x01R\x06volume\"\xc6\x01\n" +
	"\x11OrderBookSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x04bids\x18\x04 \x03(\v2\x11.proto.OrderLevelR\x04bids\x12%\n" +
	"\x04asks\x18\x05 \x03(\v2\x11.proto.OrderLevelR\x04asks\x12\x1f\n" +
	"\vlast_update\x18\x06 \x01(\tR\n" +
	"lastUpdateB\x1eZ\x1cnobitex/radar/internal/protob\x06proto3"

var (
	file_internal_proto_radar_proto_rawDescOnce sync.Once
	file_internal_proto_radar_proto_rawDescData []byte
)

func file_internal_proto_radar_proto_rawDescGZIP() []byte {
	file_internal_proto_radar_proto_rawDescOnce.Do(func() {
		file_internal_proto_radar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)))
	})
	return file_internal_proto_radar_proto_rawDescData
}

var file_internal_proto_radar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_radar_proto_goTypes = []any{
	(*TradeData)(nil),         // 0: proto.TradeData
	(*CandleData)(nil),        // 1: proto.CandleData
	(*OrderLevel)(nil),        // 2: proto.OrderLevel
	(*OrderBookSnapshot)(nil), // 3: proto.OrderBookSnapshot
}
var file_internal_proto_radar_proto_depIdxs = []int32{
	2, // 0: proto.OrderBookSnapshot.bids:type_name -> proto.OrderLevel
	2, // 1: proto.OrderBookSnapshot.asks:type_name -> proto.OrderLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_radar_proto_init() }
func file_internal_proto_radar_proto_init() {
	if File_internal_proto_radar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_radar_proto_rawDesc), len(file_internal_proto_radar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_radar_proto_goTypes,
		DependencyIndexes: file_internal_proto_radar_proto_depIdxs,
		MessageInfos:      file_internal_proto_radar_proto_msgTypes,
	}.Build()
	File_internal_proto_radar_proto = out.File
	file_internal_proto_radar_proto_goTypes = nil
	file_internal_proto_radar_proto_depIdxs = nil
}
