// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/trade.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // ID of each trade which is Unique, some exchanges return this. For others, we generate it
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                      // Name of exchange we are scrapping
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                          // Market symbol: BTCIRT,BTCUSDT
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                          // Price of Market
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`                        // volume of trade
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // result of price * volume
	Side          string                 `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`                              // buy or sell or all ("all" for aggregate API like coingecko)
	Time          string                 `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`                              // date time that trade happened
	UsdtPrice     float64                `protobuf:"fixed64,9,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"` // latest price of USDT/IRT market
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeData) Reset() {
	*x = TradeData{}
	mi := &file_proto_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeData) ProtoMessage() {}

func (x *TradeData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeData.ProtoReflect.Descriptor instead.
func (*TradeData) Descriptor() ([]byte, []int) {
	return file_proto_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TradeData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradeData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeData) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeData) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeData) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TradeData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TradeData) GetUsdtPrice() float64 {
	if x != nil {
		return x.UsdtPrice
	}
	return 0
}

type TradeDataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*TradeData           `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeDataBatch) Reset() {
	*x = TradeDataBatch{}
	mi := &file_proto_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeDataBatch) ProtoMessage() {}

func (x *TradeDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeDataBatch.ProtoReflect.Descriptor instead.
func (*TradeDataBatch) Descriptor() ([]byte, []int) {
	return file_proto_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeDataBatch) GetTrades() []*TradeData {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_proto_trade_proto protoreflect.FileDescriptor

const file_proto_trade_proto_rawDesc = "" +
	"\n" +
	"\x11proto/trade.proto\x12\x05proto\"\xe0\x01\n" +
	"\tTradeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x12\n" +
	"\x04side\x18\a \x01(\tR\x04side\x12\x12\n" +
	"\x04time\x18\b \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\t \x01(\x01R\tusdtPrice\":\n" +
	"\x0eTradeDataBatch\x12(\n" +
	"\x06trades\x18\x01 \x03(\v2\x10.proto.TradeDataR\x06tradesB\x15Z\x13nobitex/radar/protob\x06proto3"

var (
	file_proto_trade_proto_rawDescOnce sync.Once
	file_proto_trade_proto_rawDescData []byte
)

func file_proto_trade_proto_rawDescGZIP() []byte {
	file_proto_trade_proto_rawDescOnce.Do(func() {
		file_proto_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trade_proto_rawDesc), len(file_proto_trade_proto_rawDesc)))
	})
	return file_proto_trade_proto_rawDescData
}

var file_proto_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trade_proto_goTypes = []any{
	(*TradeData)(nil),      // 0: proto.TradeData
	(*TradeDataBatch)(nil), // 1: proto.TradeDataBatch
}
var file_proto_trade_proto_depIdxs = []int32{
	0, // 0: proto.TradeDataBatch.trades:type_name -> proto.TradeData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trade_proto_init() }
func file_proto_trade_proto_init() {
	if File_proto_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trade_proto_rawDesc), len(file_proto_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trade_proto_goTypes,
		DependencyIndexes: file_proto_trade_proto_depIdxs,
		MessageInfos:      file_proto_trade_proto_msgTypes,
	}.Build()
	File_proto_trade_proto = out.File
	file_proto_trade_proto_goTypes = nil
	file_proto_trade_proto_depIdxs = nil
}
